kind: pipeline
name: default

steps:
- name: fetch
  image: alpine/git
  commands:
  - which make || apk add make
  - make fetch

- name: build_upload_all
  image: openjdk:13-alpine
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_key
  commands:
  - which make || apk add make
  - which git || apk add git
  - which pip || apk add --update python py-pip python-dev
  - which aws || pip install awscli
  - sh build_upload_all.sh
